// 譜面定数参照など
// オンゲキスコアツールに感謝
// https://ongeki-score.net/music
// データ提供者の方々に感謝
/* 
  Twitter@Rinsaku471
  Twitter@RKS49019722
  Twitter@masa_9713 
*/

// 3/2作成
const constantTable = [
{title: "Opfer", diff: 3, constant: 14.9},
{title: "Titania", diff: 3, constant: 14.9},
{title: "YURUSHITE", diff: 3, constant: 14.6},
{title: "怒槌", diff: 3, constant: 14.5},
{title: "混沌を越えし我らが神聖なる調律主を讃えよ", diff: 3, constant: 14.5},
{title: "MEGATON BLAST", diff: 3, constant: 14.5},
{title: "神威", diff: 3, constant: 14.3},
{title: "エンドマークに希望と涙を添えて", diff: 3, constant: 14.2},
{title: "Dazzle hop", diff: 3, constant: 14.2},
{title: "Everlasting Today", diff: 3, constant: 14.1},
{title: "7thSense", diff: 3, constant: 14.0},
{title: "No Remorse", diff: 4, constant: 14.0},
{title: "初音ミクの激唱", diff: 3, constant: 13.9},
{title: "初音ミクの激唱", diff: 4, constant: 13.9},
{title: "閃鋼のブリューナク", diff: 3, constant: 13.9},
{title: "GOODRAGE", diff: 3, constant: 13.9},
{title: "ナイト・オブ・ナイツ", diff: 4, constant: 13.8},
{title: "Oshama Scramble!", diff: 3, constant: 13.8},
{title: "Ai Nov", diff: 3, constant: 13.8},
{title: "カミサマネジマキ", diff: 3, constant: 13.8},
{title: "Calamity Fortune", diff: 3, constant: 13.8},
{title: "ぼくらの16bit戦争", diff: 3, constant: 13.7},
{title: "Destiny Runner", diff: 3, constant: 13.7},
{title: "最終鬼畜妹フランドール・Ｓ", diff: 3, constant: 13.7},
{title: "AMAZING MIGHTYYYY!!!!", diff: 3, constant: 13.7},
{title: "Halcyon", diff: 3, constant: 13.6},
{title: "Dolphika", diff: 3, constant: 13.6},
{title: "Maqrite", diff: 3, constant: 13.6},
{title: "クイーンオブハート", diff: 3, constant: 13.6},
{title: "Gate of Doom", diff: 3, constant: 13.5},
{title: "今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～", diff: 3, constant: 13.5},
{title: "Sword of Secret", diff: 3, constant: 13.5},
{title: "Brain Power", diff: 3, constant: 13.4},
{title: "We Gonna Journey", diff: 3, constant: 13.4},
{title: "Kattobi KEIKYU Rider", diff: 3, constant: 13.4},
{title: "Opfer", diff: 2, constant: 13.3},
{title: "Titania", diff: 2, constant: 13.3},
{title: "Cyberozar", diff: 3, constant: 13.2},
{title: "幸せになれる隠しコマンドがあるらしい", diff: 3, constant: 13.2},
{title: "TAKE ON THE WORLD", diff: 3, constant: 13.2},
{title: "MEGATON BLAST", diff: 2, constant: 13.2},
{title: "脳漿炸裂ガール", diff: 3, constant: 13.1},
{title: "ブツメツビーターズ", diff: 3, constant: 13.1},
{title: "アンハッピーリフレイン", diff: 3, constant: 13.1},
{title: "ようこそジャパリパークへ", diff: 4, constant: 13.0},
{title: "鬼KYOKAN", diff: 3, constant: 13.0},
{title: "幻想のサテライト", diff: 3, constant: 13.0},
{title: "Paqqin", diff: 3, constant: 13.0},
{title: "ロボットプラネットユートピア", diff: 3, constant: 13.0},
{title: "天火明命", diff: 3, constant: 12.9},
{title: "oboro", diff: 3, constant: 12.9},
{title: "P！P！P！P！がおー!!", diff: 3, constant: 12.9},
{title: "Opera of the wasteland", diff: 3, constant: 12.9},
{title: "ゴーカ！ごーかい！？ファントムシーフ！", diff: 3, constant: 12.9},
{title: "混沌を越えし我らが神聖なる調律主を讃えよ", diff: 2, constant: 12.9},
{title: "Link with U", diff: 3, constant: 12.9},
{title: "TeA", diff: 3, constant: 12.9},
{title: "本能的 Survivor", diff: 3, constant: 12.9},
{title: "sweet little sister", diff: 3, constant: 12.8},
{title: "Hyper Active", diff: 3, constant: 12.8},
{title: "ロッキンピンクモンスター", diff: 3, constant: 12.8},
{title: "What color...", diff: 3, constant: 12.8},
{title: "God knows...", diff: 3, constant: 12.8},
{title: "時の冒険者", diff: 3, constant: 12.8},
{title: "ロキ", diff: 3, constant: 12.8},
{title: "DAYBREAK FRONTLINE", diff: 3, constant: 12.8},
{title: "Energy Booster ～ 上海紅茶館", diff: 3, constant: 12.7},
{title: "れみりあ☆デスティニー", diff: 3, constant: 12.7},
{title: "Äventyr", diff: 3, constant: 12.7},
{title: "GAME IS LIFE", diff: 3, constant: 12.7},
{title: "チュルリラ・チュルリラ・ダッダッダ！", diff: 3, constant: 12.7},
{title: "怒槌", diff: 2, constant: 12.7},
{title: "ですのっ！White & Black", diff: 3, constant: 12.7},
{title: "ヒバナ", diff: 3, constant: 12.7},
{title: "fulgente", diff: 3, constant: 12.7},
{title: "ナイト・オブ・ナイツ", diff: 3, constant: 12.6},
{title: "The Formula", diff: 3, constant: 12.6},
{title: "Here We Go", diff: 3, constant: 12.6},
{title: "SWEET SHAKE!!", diff: 3, constant: 12.6},
{title: "GranFatalité", diff: 3, constant: 12.6},
{title: "Dragoon", diff: 3, constant: 12.6},
{title: "Jump!! Jump!! Jump!!", diff: 3, constant: 12.6},
{title: "ファッとして桃源郷", diff: 3, constant: 12.5},
{title: "かくしん的☆めたまるふぉ～ぜっ!", diff: 3, constant: 12.5},
{title: "六兆年と一夜物語", diff: 3, constant: 12.5},
{title: "キミノヨゾラ哨戒班", diff: 3, constant: 12.5},
{title: "グリーンライツ・セレナーデ", diff: 3, constant: 12.5},
{title: "Bad Apple!! feat.nomico", diff: 3, constant: 12.5},
{title: "Red Battle", diff: 3, constant: 12.5},
{title: "Hey-day狂騒曲（カプリチオ）", diff: 3, constant: 12.5},
{title: "Redo", diff: 3, constant: 12.5},
{title: "超電磁少女Days", diff: 3, constant: 12.5},
{title: "木彫り鯰と右肩ゾンビ", diff: 3, constant: 12.4},
{title: "四次元跳躍機関", diff: 3, constant: 12.4},
{title: "Mare Maris", diff: 3, constant: 12.4},
{title: "月に叢雲華に風", diff: 3, constant: 12.4},
{title: "STEP by STEP UP↑↑↑↑", diff: 3, constant: 12.4},
{title: "Link of Destiny", diff: 3, constant: 12.4},
{title: "Grand symphony", diff: 3, constant: 12.4},
{title: "おこちゃま戦争", diff: 3, constant: 12.3},
{title: "砂の惑星 feat. HATSUNE MIKU", diff: 3, constant: 12.3},
{title: "ＧＯ！ＧＯ！ラブリズム♥", diff: 3, constant: 12.3},
{title: "Dazzle hop", diff: 2, constant: 12.3},
{title: "YURUSHITE", diff: 2, constant: 12.3},
{title: "ゆら・ゆらRing-Dong-Dance", diff: 3, constant: 12.3},
{title: "HARMONIZE", diff: 3, constant: 12.3},
{title: "Love is MY RAIL", diff: 3, constant: 12.3},
{title: "流星", diff: 3, constant: 12.3},
{title: "Los! Los! Los!", diff: 3, constant: 12.2},
{title: "SAVIOR OF SONG", diff: 3, constant: 12.2},
{title: "ゴーストルール", diff: 3, constant: 12.2},
{title: "心象蜃気楼", diff: 3, constant: 12.2},
{title: "天ノ弱", diff: 3, constant: 12.1},
{title: "ヒビカセ", diff: 3, constant: 12.1},
{title: "Everlasting Today", diff: 2, constant: 12.1},
{title: "sister's noise", diff: 3, constant: 12.1},
{title: "回レ！雪月花", diff: 3, constant: 12.0},
{title: "Grip & Break down !!", diff: 3, constant: 12.0},
{title: "アクアテラリウム", diff: 3, constant: 12.0},
{title: "オモイヨシノ", diff: 3, constant: 12.0},
{title: "神威", diff: 2, constant: 12.0},
{title: "Zest of Blue", diff: 3, constant: 12.0},
{title: "タテマエと本心の大乱闘", diff: 3, constant: 12.0},
{title: "TOMORROW", diff: 3, constant: 12.0},
{title: "こころここから", diff: 3, constant: 12.0},
{title: "ようこそジャパリパークへ", diff: 3, constant: 11.9},
{title: "Red “reduction division” -crossroads version-", diff: 3, constant: 11.9},
{title: "いーあるふぁんくらぶ", diff: 3, constant: 11.9},
{title: "CiRCLING", diff: 3, constant: 11.9},
{title: "Calamity Fortune", diff: 2, constant: 11.9},
{title: "千本桜", diff: 3, constant: 11.8},
{title: "エンドマークに希望と涙を添えて", diff: 2, constant: 11.8},
{title: "シュガーソングとビターステップ", diff: 3, constant: 11.7},
{title: "BLACK SHOUT", diff: 3, constant: 11.7},
{title: "ブリキノダンス", diff: 3, constant: 11.7},
{title: "7thSense", diff: 2, constant: 11.7},
{title: "カミサマネジマキ", diff: 2, constant: 11.7},
{title: "only my railgun", diff: 3, constant: 11.7},
{title: "This game", diff: 3, constant: 11.6},
{title: "GOODRAGE", diff: 2, constant: 11.5},
{title: "Perfect Shining!!", diff: 3, constant: 11.4},
{title: "みんな Happy!!", diff: 3, constant: 11.4},
{title: "わたし音頭", diff: 3, constant: 11.4},
{title: "鳥の詩", diff: 3, constant: 11.0},
{title: "That Is How I Roll!", diff: 3, constant: 11.0},
{title: "檄!帝国華撃団", diff: 3, constant: 11.0},
{title: "Halcyon", diff: 2, constant: 11.0},
{title: "Hyper Active", diff: 2, constant: 11.0},
{title: "Gate of Doom", diff: 2, constant: 11.0},
{title: "First Twinkle", diff: 3, constant: 11.0},
{title: "STARTLINER", diff: 3, constant: 11.0},
{title: "Ai Nov", diff: 2, constant: 11.0},
{title: "secret base ～君がくれたもの～ (10 years after Ver.)", diff: 3, constant: 11.0},
{title: "カンペキWill", diff: 3, constant: 11.0},
{title: "アンハッピーリフレイン", diff: 2, constant: 11.0},
{title: "SAKURA", diff: 3, constant: 10.7},
{title: "しゅわりん☆どり〜みん", diff: 3, constant: 10.7},
{title: "初音ミクの激唱", diff: 2, constant: 10.7},
{title: "AMAZING MIGHTYYYY!!!!", diff: 2, constant: 10.7},
{title: "Kattobi KEIKYU Rider", diff: 2, constant: 10.7},
{title: "Dolphika", diff: 2, constant: 10.7},
{title: "ロッキンピンクモンスター", diff: 2, constant: 10.7},
{title: "連れ去って・閉じ込めて・好きにして", diff: 3, constant: 10.7},
{title: "君の知らない物語", diff: 3, constant: 10.0},
{title: "ときめきエクスペリエンス！", diff: 3, constant: 10.0},
{title: "えがおのオーケストラっ！", diff: 3, constant: 10.0},
{title: "脳漿炸裂ガール", diff: 2, constant: 10.0},
{title: "鬼KYOKAN", diff: 2, constant: 10.0},
{title: "ぼくらの16bit戦争", diff: 2, constant: 10.0},
{title: "幻想のサテライト", diff: 2, constant: 10.0},
{title: "Destiny Runner", diff: 2, constant: 10.0},
{title: "最終鬼畜妹フランドール・Ｓ", diff: 2, constant: 10.0},
{title: "Oshama Scramble!", diff: 2, constant: 10.0},
{title: "Cyberozar", diff: 2, constant: 10.0},
{title: "Paqqin", diff: 2, constant: 10.0},
{title: "We Gonna Journey", diff: 2, constant: 10.0},
{title: "閃鋼のブリューナク", diff: 2, constant: 10.0},
{title: "P！P！P！P！がおー!!", diff: 2, constant: 10.0},
{title: "チュルリラ・チュルリラ・ダッダッダ！", diff: 2, constant: 10.0},
{title: "ロボットプラネットユートピア", diff: 2, constant: 10.0},
{title: "クイーンオブハート", diff: 2, constant: 10.0},
{title: "TAKE ON THE WORLD", diff: 2, constant: 10.0},
{title: "TeA", diff: 2, constant: 10.0},
{title: "木彫り鯰と右肩ゾンビ", diff: 2, constant: 9.7},
{title: "ゴーストルール", diff: 2, constant: 9.7},
{title: "ナイト・オブ・ナイツ", diff: 2, constant: 9.7},
{title: "The Formula", diff: 2, constant: 9.7},
{title: "Brain Power", diff: 2, constant: 9.7},
{title: "天火明命", diff: 2, constant: 9.7},
{title: "今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～", diff: 2, constant: 9.7},
{title: "Zest of Blue", diff: 2, constant: 9.7},
{title: "タテマエと本心の大乱闘", diff: 2, constant: 9.7},
{title: "ブツメツビーターズ", diff: 2, constant: 9.7},
{title: "Sword of Secret", diff: 2, constant: 9.7},
{title: "Maqrite", diff: 2, constant: 9.7},
{title: "GAME IS LIFE", diff: 2, constant: 9.7},
{title: "幸せになれる隠しコマンドがあるらしい", diff: 2, constant: 9.7},
{title: "ゴーカ！ごーかい！？ファントムシーフ！", diff: 2, constant: 9.7},
{title: "Titania", diff: 1, constant: 9.7},
{title: "Link with U", diff: 2, constant: 9.7},
{title: "時の冒険者", diff: 2, constant: 9.7},
{title: "ヒバナ", diff: 2, constant: 9.7},
{title: "本能的 Survivor", diff: 2, constant: 9.7},
{title: "回レ！雪月花", diff: 2, constant: 9.0},
{title: "Red “reduction division” -crossroads version-", diff: 2, constant: 9.0},
{title: "That Is How I Roll!", diff: 2, constant: 9.0},
{title: "BLACK SHOUT", diff: 2, constant: 9.0},
{title: "天ノ弱", diff: 2, constant: 9.0},
{title: "おこちゃま戦争", diff: 2, constant: 9.0},
{title: "六兆年と一夜物語", diff: 2, constant: 9.0},
{title: "キミノヨゾラ哨戒班", diff: 2, constant: 9.0},
{title: "ヒビカセ", diff: 2, constant: 9.0},
{title: "グリーンライツ・セレナーデ", diff: 2, constant: 9.0},
{title: "ブリキノダンス", diff: 2, constant: 9.0},
{title: "Grip & Break down !!", diff: 2, constant: 9.0},
{title: "Energy Booster ～ 上海紅茶館", diff: 2, constant: 9.0},
{title: "れみりあ☆デスティニー", diff: 2, constant: 9.0},
{title: "sweet little sister", diff: 2, constant: 9.0},
{title: "オモイヨシノ", diff: 2, constant: 9.0},
{title: "ＧＯ！ＧＯ！ラブリズム♥", diff: 2, constant: 9.0},
{title: "Mare Maris", diff: 2, constant: 9.0},
{title: "First Twinkle", diff: 2, constant: 9.0},
{title: "oboro", diff: 2, constant: 9.0},
{title: "みんな Happy!!", diff: 2, constant: 9.0},
{title: "Here We Go", diff: 2, constant: 9.0},
{title: "What color...", diff: 2, constant: 9.0},
{title: "GranFatalité", diff: 2, constant: 9.0},
{title: "Dazzle hop", diff: 1, constant: 9.0},
{title: "YURUSHITE", diff: 1, constant: 9.0},
{title: "Dragoon", diff: 2, constant: 9.0},
{title: "Hey-day狂騒曲（カプリチオ）", diff: 2, constant: 9.0},
{title: "ゆら・ゆらRing-Dong-Dance", diff: 2, constant: 9.0},
{title: "Opera of the wasteland", diff: 2, constant: 9.0},
{title: "Opfer", diff: 1, constant: 9.0},
{title: "God knows...", diff: 2, constant: 9.0},
{title: "STEP by STEP UP↑↑↑↑", diff: 2, constant: 9.0},
{title: "Link of Destiny", diff: 2, constant: 9.0},
{title: "Love is MY RAIL", diff: 2, constant: 9.0},
{title: "Redo", diff: 2, constant: 9.0},
{title: "Grand symphony", diff: 2, constant: 9.0},
{title: "sister's noise", diff: 2, constant: 9.0},
{title: "Jump!! Jump!! Jump!!", diff: 2, constant: 9.0},
{title: "only my railgun", diff: 2, constant: 9.0},
{title: "DAYBREAK FRONTLINE", diff: 2, constant: 9.0},
{title: "MEGATON BLAST", diff: 1, constant: 9.0},
{title: "This game", diff: 2, constant: 8.7},
{title: "Los! Los! Los!", diff: 2, constant: 8.7},
{title: "しゅわりん☆どり〜みん", diff: 2, constant: 8.7},
{title: "千本桜", diff: 2, constant: 8.7},
{title: "砂の惑星 feat. HATSUNE MIKU", diff: 2, constant: 8.7},
{title: "Äventyr", diff: 2, constant: 8.7},
{title: "心象蜃気楼", diff: 2, constant: 8.7},
{title: "エンドマークに希望と涙を添えて", diff: 1, constant: 8.7},
{title: "STARTLINER", diff: 2, constant: 8.7},
{title: "SWEET SHAKE!!", diff: 2, constant: 8.7},
{title: "TOMORROW", diff: 2, constant: 8.7},
{title: "Red Battle", diff: 2, constant: 8.7},
{title: "月に叢雲華に風", diff: 2, constant: 8.7},
{title: "CiRCLING", diff: 2, constant: 8.7},
{title: "怒槌", diff: 1, constant: 8.7},
{title: "混沌を越えし我らが神聖なる調律主を讃えよ", diff: 1, constant: 8.7},
{title: "HARMONIZE", diff: 2, constant: 8.7},
{title: "こころここから", diff: 2, constant: 8.7},
{title: "流星", diff: 2, constant: 8.7},
{title: "ですのっ！White & Black", diff: 2, constant: 8.7},
{title: "ロキ", diff: 2, constant: 8.7},
{title: "fulgente", diff: 2, constant: 8.7},
{title: "ようこそジャパリパークへ", diff: 2, constant: 8.0},
{title: "ファッとして桃源郷", diff: 2, constant: 8.0},
{title: "かくしん的☆めたまるふぉ～ぜっ!", diff: 2, constant: 8.0},
{title: "SAVIOR OF SONG", diff: 2, constant: 8.0},
{title: "鳥の詩", diff: 2, constant: 8.0},
{title: "SAKURA", diff: 2, constant: 8.0},
{title: "ときめきエクスペリエンス！", diff: 2, constant: 8.0},
{title: "えがおのオーケストラっ！", diff: 2, constant: 8.0},
{title: "Bad Apple!! feat.nomico", diff: 2, constant: 8.0},
{title: "アクアテラリウム", diff: 2, constant: 8.0},
{title: "四次元跳躍機関", diff: 2, constant: 8.0},
{title: "神威", diff: 1, constant: 8.0},
{title: "Perfect Shining!!", diff: 2, constant: 8.0},
{title: "いーあるふぁんくらぶ", diff: 2, constant: 8.0},
{title: "わたし音頭", diff: 2, constant: 8.0},
{title: "連れ去って・閉じ込めて・好きにして", diff: 2, constant: 8.0},
{title: "secret base ～君がくれたもの～ (10 years after Ver.)", diff: 2, constant: 8.0},
{title: "超電磁少女Days", diff: 2, constant: 8.0},
{title: "Calamity Fortune", diff: 1, constant: 8.0},
{title: "カンペキWill", diff: 2, constant: 8.0},
{title: "君の知らない物語", diff: 2, constant: 7.7},
{title: "シュガーソングとビターステップ", diff: 2, constant: 7.7},
{title: "初音ミクの激唱", diff: 1, constant: 7.7},
{title: "檄!帝国華撃団", diff: 2, constant: 7.7},
{title: "Halcyon", diff: 1, constant: 7.7},
{title: "Hyper Active", diff: 1, constant: 7.7},
{title: "Gate of Doom", diff: 1, constant: 7.7},
{title: "閃鋼のブリューナク", diff: 1, constant: 7.7},
{title: "7thSense", diff: 1, constant: 7.7},
{title: "Kattobi KEIKYU Rider", diff: 1, constant: 7.7},
{title: "P！P！P！P！がおー!!", diff: 1, constant: 7.7},
{title: "Ai Nov", diff: 1, constant: 7.7},
{title: "Everlasting Today", diff: 1, constant: 7.7},
{title: "GOODRAGE", diff: 1, constant: 7.7},
{title: "クイーンオブハート", diff: 1, constant: 7.7},
{title: "SAVIOR OF SONG", diff: 1, constant: 7.0},
{title: "ナイト・オブ・ナイツ", diff: 1, constant: 7.0},
{title: "幻想のサテライト", diff: 1, constant: 7.0},
{title: "Destiny Runner", diff: 1, constant: 7.0},
{title: "最終鬼畜妹フランドール・Ｓ", diff: 1, constant: 7.0},
{title: "The Formula", diff: 1, constant: 7.0},
{title: "Oshama Scramble!", diff: 1, constant: 7.0},
{title: "Mare Maris", diff: 1, constant: 7.0},
{title: "AMAZING MIGHTYYYY!!!!", diff: 1, constant: 7.0},
{title: "We Gonna Journey", diff: 1, constant: 7.0},
{title: "今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～", diff: 1, constant: 7.0},
{title: "ロッキンピンクモンスター", diff: 1, constant: 7.0},
{title: "ブツメツビーターズ", diff: 1, constant: 7.0},
{title: "Sword of Secret", diff: 1, constant: 7.0},
{title: "GAME IS LIFE", diff: 1, constant: 7.0},
{title: "GranFatalité", diff: 1, constant: 7.0},
{title: "カミサマネジマキ", diff: 1, constant: 7.0},
{title: "幸せになれる隠しコマンドがあるらしい", diff: 1, constant: 7.0},
{title: "チュルリラ・チュルリラ・ダッダッダ！", diff: 1, constant: 7.0},
{title: "ゴーカ！ごーかい！？ファントムシーフ！", diff: 1, constant: 7.0},
{title: "Love is MY RAIL", diff: 1, constant: 7.0},
{title: "Link with U", diff: 1, constant: 7.0},
{title: "ロボットプラネットユートピア", diff: 1, constant: 7.0},
{title: "時の冒険者", diff: 1, constant: 7.0},
{title: "ヒバナ", diff: 1, constant: 7.0},
{title: "TAKE ON THE WORLD", diff: 1, constant: 7.0},
{title: "TeA", diff: 1, constant: 7.0},
{title: "アンハッピーリフレイン", diff: 1, constant: 7.0},
{title: "本能的 Survivor", diff: 1, constant: 7.0},
{title: "回レ！雪月花", diff: 1, constant: 6.0},
{title: "ようこそジャパリパークへ", diff: 1, constant: 6.0},
{title: "ファッとして桃源郷", diff: 1, constant: 6.0},
{title: "This game", diff: 1, constant: 6.0},
{title: "Los! Los! Los!", diff: 1, constant: 6.0},
{title: "ときめきエクスペリエンス！", diff: 1, constant: 6.0},
{title: "しゅわりん☆どり〜みん", diff: 1, constant: 6.0},
{title: "おこちゃま戦争", diff: 1, constant: 6.0},
{title: "六兆年と一夜物語", diff: 1, constant: 6.0},
{title: "千本桜", diff: 1, constant: 6.0},
{title: "キミノヨゾラ哨戒班", diff: 1, constant: 6.0},
{title: "木彫り鯰と右肩ゾンビ", diff: 1, constant: 6.0},
{title: "鬼KYOKAN", diff: 1, constant: 6.0},
{title: "ぼくらの16bit戦争", diff: 1, constant: 6.0},
{title: "ヒビカセ", diff: 1, constant: 6.0},
{title: "グリーンライツ・セレナーデ", diff: 1, constant: 6.0},
{title: "ゴーストルール", diff: 1, constant: 6.0},
{title: "Grip & Break down !!", diff: 1, constant: 6.0},
{title: "Energy Booster ～ 上海紅茶館", diff: 1, constant: 6.0},
{title: "れみりあ☆デスティニー", diff: 1, constant: 6.0},
{title: "sweet little sister", diff: 1, constant: 6.0},
{title: "Brain Power", diff: 1, constant: 6.0},
{title: "ＧＯ！ＧＯ！ラブリズム♥", diff: 1, constant: 6.0},
{title: "心象蜃気楼", diff: 1, constant: 6.0},
{title: "天火明命", diff: 1, constant: 6.0},
{title: "Cyberozar", diff: 1, constant: 6.0},
{title: "First Twinkle", diff: 1, constant: 6.0},
{title: "Paqqin", diff: 1, constant: 6.0},
{title: "oboro", diff: 1, constant: 6.0},
{title: "Perfect Shining!!", diff: 1, constant: 6.0},
{title: "Zest of Blue", diff: 1, constant: 6.0},
{title: "Dolphika", diff: 1, constant: 6.0},
{title: "タテマエと本心の大乱闘", diff: 1, constant: 6.0},
{title: "SWEET SHAKE!!", diff: 1, constant: 6.0},
{title: "What color...", diff: 1, constant: 6.0},
{title: "Maqrite", diff: 1, constant: 6.0},
{title: "Red Battle", diff: 1, constant: 6.0},
{title: "Dragoon", diff: 1, constant: 6.0},
{title: "月に叢雲華に風", diff: 1, constant: 6.0},
{title: "CiRCLING", diff: 1, constant: 6.0},
{title: "Hey-day狂騒曲（カプリチオ）", diff: 1, constant: 6.0},
{title: "ゆら・ゆらRing-Dong-Dance", diff: 1, constant: 6.0},
{title: "Opera of the wasteland", diff: 1, constant: 6.0},
{title: "HARMONIZE", diff: 1, constant: 6.0},
{title: "God knows...", diff: 1, constant: 6.0},
{title: "STEP by STEP UP↑↑↑↑", diff: 1, constant: 6.0},
{title: "Link of Destiny", diff: 1, constant: 6.0},
{title: "Redo", diff: 1, constant: 6.0},
{title: "Grand symphony", diff: 1, constant: 6.0},
{title: "sister's noise", diff: 1, constant: 6.0},
{title: "ロキ", diff: 1, constant: 6.0},
{title: "Jump!! Jump!! Jump!!", diff: 1, constant: 6.0},
{title: "fulgente", diff: 1, constant: 6.0},
{title: "only my railgun", diff: 1, constant: 6.0},
{title: "DAYBREAK FRONTLINE", diff: 1, constant: 6.0},
{title: "君の知らない物語", diff: 1, constant: 5.0},
{title: "シュガーソングとビターステップ", diff: 1, constant: 5.0},
{title: "かくしん的☆めたまるふぉ～ぜっ!", diff: 1, constant: 5.0},
{title: "Red “reduction division” -crossroads version-", diff: 1, constant: 5.0},
{title: "鳥の詩", diff: 1, constant: 5.0},
{title: "SAKURA", diff: 1, constant: 5.0},
{title: "That Is How I Roll!", diff: 1, constant: 5.0},
{title: "BLACK SHOUT", diff: 1, constant: 5.0},
{title: "えがおのオーケストラっ！", diff: 1, constant: 5.0},
{title: "脳漿炸裂ガール", diff: 1, constant: 5.0},
{title: "天ノ弱", diff: 1, constant: 5.0},
{title: "砂の惑星 feat. HATSUNE MIKU", diff: 1, constant: 5.0},
{title: "ブリキノダンス", diff: 1, constant: 5.0},
{title: "Bad Apple!! feat.nomico", diff: 1, constant: 5.0},
{title: "アクアテラリウム", diff: 1, constant: 5.0},
{title: "四次元跳躍機関", diff: 1, constant: 5.0},
{title: "檄!帝国華撃団", diff: 1, constant: 5.0},
{title: "オモイヨシノ", diff: 1, constant: 5.0},
{title: "Äventyr", diff: 1, constant: 5.0},
{title: "STARTLINER", diff: 1, constant: 5.0},
{title: "みんな Happy!!", diff: 1, constant: 5.0},
{title: "Here We Go", diff: 1, constant: 5.0},
{title: "Dazzle hop", diff: 0, constant: 5.0},
{title: "TOMORROW", diff: 1, constant: 5.0},
{title: "いーあるふぁんくらぶ", diff: 1, constant: 5.0},
{title: "わたし音頭", diff: 1, constant: 5.0},
{title: "連れ去って・閉じ込めて・好きにして", diff: 1, constant: 5.0},
{title: "混沌を越えし我らが神聖なる調律主を讃えよ", diff: 0, constant: 5.0},
{title: "Titania", diff: 0, constant: 5.0},
{title: "secret base ～君がくれたもの～ (10 years after Ver.)", diff: 1, constant: 5.0},
{title: "こころここから", diff: 1, constant: 5.0},
{title: "流星", diff: 1, constant: 5.0},
{title: "超電磁少女Days", diff: 1, constant: 5.0},
{title: "ですのっ！White & Black", diff: 1, constant: 5.0},
{title: "カンペキWill", diff: 1, constant: 5.0},
{title: "MEGATON BLAST", diff: 0, constant: 5.0},
{title: "鬼KYOKAN", diff: 0, constant: 4.0},
{title: "初音ミクの激唱", diff: 0, constant: 4.0},
{title: "The Formula", diff: 0, constant: 4.0},
{title: "Brain Power", diff: 0, constant: 4.0},
{title: "Halcyon", diff: 0, constant: 4.0},
{title: "神威", diff: 0, constant: 4.0},
{title: "Oshama Scramble!", diff: 0, constant: 4.0},
{title: "Cyberozar", diff: 0, constant: 4.0},
{title: "AMAZING MIGHTYYYY!!!!", diff: 0, constant: 4.0},
{title: "Gate of Doom", diff: 0, constant: 4.0},
{title: "閃鋼のブリューナク", diff: 0, constant: 4.0},
{title: "7thSense", diff: 0, constant: 4.0},
{title: "エンドマークに希望と涙を添えて", diff: 0, constant: 4.0},
{title: "P！P！P！P！がおー!!", diff: 0, constant: 4.0},
{title: "タテマエと本心の大乱闘", diff: 0, constant: 4.0},
{title: "Ai Nov", diff: 0, constant: 4.0},
{title: "YURUSHITE", diff: 0, constant: 4.0},
{title: "GOODRAGE", diff: 0, constant: 4.0},
{title: "怒槌", diff: 0, constant: 4.0},
{title: "Opfer", diff: 0, constant: 4.0},
{title: "Link with U", diff: 0, constant: 4.0},
{title: "時の冒険者", diff: 0, constant: 4.0},
{title: "クイーンオブハート", diff: 0, constant: 4.0},
{title: "Calamity Fortune", diff: 0, constant: 4.0},
{title: "アンハッピーリフレイン", diff: 0, constant: 4.0},
{title: "回レ！雪月花", diff: 0, constant: 3.0},
{title: "ようこそジャパリパークへ", diff: 0, constant: 3.0},
{title: "ファッとして桃源郷", diff: 0, constant: 3.0},
{title: "かくしん的☆めたまるふぉ～ぜっ!", diff: 0, constant: 3.0},
{title: "This game", diff: 0, constant: 3.0},
{title: "SAVIOR OF SONG", diff: 0, constant: 3.0},
{title: "脳漿炸裂ガール", diff: 0, constant: 3.0},
{title: "天ノ弱", diff: 0, constant: 3.0},
{title: "おこちゃま戦争", diff: 0, constant: 3.0},
{title: "六兆年と一夜物語", diff: 0, constant: 3.0},
{title: "キミノヨゾラ哨戒班", diff: 0, constant: 3.0},
{title: "木彫り鯰と右肩ゾンビ", diff: 0, constant: 3.0},
{title: "ぼくらの16bit戦争", diff: 0, constant: 3.0},
{title: "グリーンライツ・セレナーデ", diff: 0, constant: 3.0},
{title: "ゴーストルール", diff: 0, constant: 3.0},
{title: "ナイト・オブ・ナイツ", diff: 0, constant: 3.0},
{title: "Grip & Break down !!", diff: 0, constant: 3.0},
{title: "幻想のサテライト", diff: 0, constant: 3.0},
{title: "Energy Booster ～ 上海紅茶館", diff: 0, constant: 3.0},
{title: "れみりあ☆デスティニー", diff: 0, constant: 3.0},
{title: "sweet little sister", diff: 0, constant: 3.0},
{title: "Destiny Runner", diff: 0, constant: 3.0},
{title: "最終鬼畜妹フランドール・Ｓ", diff: 0, constant: 3.0},
{title: "オモイヨシノ", diff: 0, constant: 3.0},
{title: "ＧＯ！ＧＯ！ラブリズム♥", diff: 0, constant: 3.0},
{title: "Mare Maris", diff: 0, constant: 3.0},
{title: "Hyper Active", diff: 0, constant: 3.0},
{title: "天火明命", diff: 0, constant: 3.0},
{title: "Paqqin", diff: 0, constant: 3.0},
{title: "We Gonna Journey", diff: 0, constant: 3.0},
{title: "今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～", diff: 0, constant: 3.0},
{title: "Kattobi KEIKYU Rider", diff: 0, constant: 3.0},
{title: "Perfect Shining!!", diff: 0, constant: 3.0},
{title: "Zest of Blue", diff: 0, constant: 3.0},
{title: "Dolphika", diff: 0, constant: 3.0},
{title: "ロッキンピンクモンスター", diff: 0, constant: 3.0},
{title: "ブツメツビーターズ", diff: 0, constant: 3.0},
{title: "Sword of Secret", diff: 0, constant: 3.0},
{title: "Everlasting Today", diff: 0, constant: 3.0},
{title: "GAME IS LIFE", diff: 0, constant: 3.0},
{title: "GranFatalité", diff: 0, constant: 3.0},
{title: "カミサマネジマキ", diff: 0, constant: 3.0},
{title: "チュルリラ・チュルリラ・ダッダッダ！", diff: 0, constant: 3.0},
{title: "Dragoon", diff: 0, constant: 3.0},
{title: "月に叢雲華に風", diff: 0, constant: 3.0},
{title: "ゆら・ゆらRing-Dong-Dance", diff: 0, constant: 3.0},
{title: "ゴーカ！ごーかい！？ファントムシーフ！", diff: 0, constant: 3.0},
{title: "STEP by STEP UP↑↑↑↑", diff: 0, constant: 3.0},
{title: "Love is MY RAIL", diff: 0, constant: 3.0},
{title: "ロボットプラネットユートピア", diff: 0, constant: 3.0},
{title: "Redo", diff: 0, constant: 3.0},
{title: "Grand symphony", diff: 0, constant: 3.0},
{title: "ヒバナ", diff: 0, constant: 3.0},
{title: "ロキ", diff: 0, constant: 3.0},
{title: "Jump!! Jump!! Jump!!", diff: 0, constant: 3.0},
{title: "TAKE ON THE WORLD", diff: 0, constant: 3.0},
{title: "TeA", diff: 0, constant: 3.0},
{title: "本能的 Survivor", diff: 0, constant: 3.0},
{title: "君の知らない物語", diff: 0, constant: 2.0},
{title: "シュガーソングとビターステップ", diff: 0, constant: 2.0},
{title: "Los! Los! Los!", diff: 0, constant: 2.0},
{title: "Red “reduction division” -crossroads version-", diff: 0, constant: 2.0},
{title: "SAKURA", diff: 0, constant: 2.0},
{title: "ときめきエクスペリエンス！", diff: 0, constant: 2.0},
{title: "That Is How I Roll!", diff: 0, constant: 2.0},
{title: "しゅわりん☆どり〜みん", diff: 0, constant: 2.0},
{title: "BLACK SHOUT", diff: 0, constant: 2.0},
{title: "えがおのオーケストラっ！", diff: 0, constant: 2.0},
{title: "千本桜", diff: 0, constant: 2.0},
{title: "ヒビカセ", diff: 0, constant: 2.0},
{title: "砂の惑星 feat. HATSUNE MIKU", diff: 0, constant: 2.0},
{title: "ブリキノダンス", diff: 0, constant: 2.0},
{title: "Bad Apple!! feat.nomico", diff: 0, constant: 2.0},
{title: "アクアテラリウム", diff: 0, constant: 2.0},
{title: "四次元跳躍機関", diff: 0, constant: 2.0},
{title: "檄!帝国華撃団", diff: 0, constant: 2.0},
{title: "Äventyr", diff: 0, constant: 2.0},
{title: "心象蜃気楼", diff: 0, constant: 2.0},
{title: "First Twinkle", diff: 0, constant: 2.0},
{title: "oboro", diff: 0, constant: 2.0},
{title: "STARTLINER", diff: 0, constant: 2.0},
{title: "みんな Happy!!", diff: 0, constant: 2.0},
{title: "Here We Go", diff: 0, constant: 2.0},
{title: "SWEET SHAKE!!", diff: 0, constant: 2.0},
{title: "What color...", diff: 0, constant: 2.0},
{title: "Maqrite", diff: 0, constant: 2.0},
{title: "TOMORROW", diff: 0, constant: 2.0},
{title: "いーあるふぁんくらぶ", diff: 0, constant: 2.0},
{title: "幸せになれる隠しコマンドがあるらしい", diff: 0, constant: 2.0},
{title: "CiRCLING", diff: 0, constant: 2.0},
{title: "Hey-day狂騒曲（カプリチオ）", diff: 0, constant: 2.0},
{title: "Opera of the wasteland", diff: 0, constant: 2.0},
{title: "HARMONIZE", diff: 0, constant: 2.0},
{title: "God knows...", diff: 0, constant: 2.0},
{title: "Link of Destiny", diff: 0, constant: 2.0},
{title: "流星", diff: 0, constant: 2.0},
{title: "sister's noise", diff: 0, constant: 2.0},
{title: "超電磁少女Days", diff: 0, constant: 2.0},
{title: "ですのっ！White & Black", diff: 0, constant: 2.0},
{title: "fulgente", diff: 0, constant: 2.0},
{title: "only my railgun", diff: 0, constant: 2.0},
{title: "カンペキWill", diff: 0, constant: 2.0},
{title: "DAYBREAK FRONTLINE", diff: 0, constant: 2.0},
{title: "鳥の詩", diff: 0, constant: 1.0},
{title: "Red Battle", diff: 0, constant: 1.0},
{title: "わたし音頭", diff: 0, constant: 1.0},
{title: "連れ去って・閉じ込めて・好きにして", diff: 0, constant: 1.0},
{title: "secret base ～君がくれたもの～ (10 years after Ver.)", diff: 0, constant: 1.0},
{title: "こころここから", diff: 0, constant: 1.0},
];

// 指定した難易度の曲を取得
const getMusicsByDiff = function (diffList){
    let result = [];
    for (let diff of diffList)
        appendLists(result,constantTable.filter(m => m.difficulty == diff));
    return result;
}

const diffToNum = function(diffstr){
    switch(diffstr){
    case "Master":
        return 3;
    case "Expert":
        return 2;
    case "Advanced":
        return 1;
    case "Basic":
        return 0;
    default: // Lunatic
        return 4;
    }
}

// オンゲキスコアツールの定数表(https://ongeki-score.net/music)から定数を取得して表示
const getConstants = function(){
    let data = "";    
    const musicArr = [].slice.call(document.getElementsByClassName('list')[0].children);
    musicArr.forEach(function(item){
        const itemChildren = item.children;
        const musicTitle = itemChildren[0].textContent;
        const musicDiff = diffToNum(itemChildren[1].textContent);
        const musicConstant = itemChildren[3].textContent;
        data += "{title: \"" + musicTitle + "\", diff: " + musicDiff + ", constant: " + musicConstant + "},\n"
    });
    return data;
}
